### ISSUE TITLE
Add elastic exporter as optional dependency

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/camunda-cloud-helm#10]
Sometimes on our benchmarks we also want to see metrics from elastic, for that normally the [elastic-exporter](https://github.com/justwatchcom/elasticsearch_exporter) is used

We configured it normally like this, in order to work with out Prometheus setup.
```
es:
  uri: "http://elasticsearch-master-headless:9200"
serviceMonitor:
  enabled: true
  labels:
    release: "metrics"
```
