### ISSUE TITLE
CCSM: Operate Deployment is using a Zeebe Image

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-community-hub/camunda-cloud-helm#161]
values.yml:
```yaml
global:
  image:
    repository: camunda/zeebe
    tag: SNAPSHOT
    pullPolicy: Always
operate:
  enabled: true
  global:
    image:
      repository: camunda/operate
zeebe:
  clusterSize: "3"
  partitionCount: "3"
  replicationFactor: "3"
....
```

generates this deployment for Operate:
```yaml
# Source: ccsm-helm/charts/operate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-benchmark-1-operate
  labels:
    app: camunda-cloud-self-managed
    app.kubernetes.io/name: operate
    helm.sh/chart: operate-0.0.9
    app.kubernetes.io/instance: os-benchmark-1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/part-of: camunda-cloud-self-managed
    app.kubernetes.io/component: operate
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels: ...
  template:
    metadata:
      labels: ...
    spec:
      containers:
      - name: operate
        image: "camunda/zeebe:SNAPSHOT"
...
```

I'd expect the `global.image.repository` overwrite for Operate to work, but I'm not too familiar with Helm.

I've found the values.yml in the Zeebe benchmarks: https://github.com/camunda-cloud/zeebe/blob/main/benchmarks/setup/default/zeebe-values.yaml#L112-L116
