### ISSUE TITLE
Setting `containerSecurityContext` generates invalid yaml 

### ISSUE THREAD

**Issue by oleschoenburg** [camunda-community-hub/camunda-cloud-helm#199]
Setting 

```yaml
zeebe:
  containerSecurityContext:
    capabilities:
      add: ["NET_ADMIN"]
```

generates this yaml: 

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "default-zeebe"
  labels: ...
  annotations:
spec:
  replicas: 3
  selector:
    matchLabels: ...
  serviceName: "default-zeebe"
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels: ...
      annotations:
    spec:
      initContainers:
      containers:
      - name: zeebe
        image: "camunda/zeebe:SNAPSHOT"
        imagePullPolicy: Always
        env: ...
        ports: ...
        readinessProbe: ...
        resources: ...
        volumeMounts: ...
        securityContext: capabilities:
              add:
              - NET_ADMIN
```

where the `securityContext` is missing a linebreak.
