### ISSUE TITLE
Make Operate resources configurable via chart values

### ISSUE THREAD

**Issue by falko** [camunda-community-hub/camunda-cloud-helm#27]
I tried:
```yaml
zeebe-operate-helm:
  resources:
    limits:
      cpu: 14
      memory: 54Gi
    requests:
      cpu: 14
      memory: 32Gi
```
in `zeebe-full-helm` to configure Operate resources similar to how it is done for `zeebe-cluster-helm`. However, I saw that the [deployment.yaml](https://github.com/camunda-community-hub/camunda-cloud-helm/blob/2d384331a218c206faa4598ceea2e8d2586b651e/charts/zeebe-operate-helm/templates/deployment.yaml#L21) is having resources hard-coded. I suggest to do it similar to [zeebe-cluster-helm's statefulset.yaml](https://github.com/camunda-community-hub/camunda-cloud-helm/blob/33aba77e8329890dc607e1ff74db485068d807cf/charts/zeebe-cluster-helm/templates/statefulset.yaml#L105).
