### ISSUE TITLE
Unclear how to configure zeebe-cluster

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/camunda-cloud-helm#3]
My problem was that I wanted to setup Zeebe with operate for our benchmarks and 
I saw that the throughput was significant lower when we use the zeebe-full instead of the zeebe-cluster chart. https://github.com/zeebe-io/zeebe-benchmark/issues/23

I used the same configuration for the full chart as for the cluster chart, the only difference was that I 
put all properties under `zeebe-cluster`.

Like:

```yaml
zeebe-cluster:
  image:
    repository: camunda/zeebe
    tag: SNAPSHOT
    pullPolicy: IfNotPresent

  # ZEEBE CFG

  clusterSize: 3
  partitionCount: 3
  replicationFactor: 3
  cpuThreadCount: 4
  ioThreadCount: 4

  ... etc.
``` 

I expected that this was the way to go since the README in this repo says the same https://github.com/zeebe-io/zeebe-full-helm. Furthermore I expected that this works that way because the chart is called liked that. 

Luckily I found [this](https://github.com/zeebe-io/zeebe-helm/issues/3#issuecomment-561618717) conversation, which shows the usage of `zeebe` instead of `zeebe-cluster`.

This fixes also my benchmark setup and worked now as expected:
```yaml
zeebe:
  image:
    repository: camunda/zeebe
    tag: SNAPSHOT
    pullPolicy: IfNotPresent

  # ZEEBE CFG

  clusterSize: 3
  partitionCount: 3
  replicationFactor: 3
  cpuThreadCount: 4
  ioThreadCount: 4

  ... etc.
``` 

We probably should add an example configuration or something like that how to configure this or we change the name to zeebe-cluster, this would things probably more clear.
