### ISSUE TITLE
can't configure podSecurityContext

### ISSUE THREAD

**Issue by sushiMix** [camunda-community-hub/camunda-cloud-helm#90]
I tried to configure podSecurityContext with zeebe-cluster-helm 1.2.10.

It fails with 
`Error: YAML parse error on zeebe-cluster-helm/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 104: mapping values are not allowed in this context
helm.go:88: [debug] error converting YAML to JSON: yaml: line 104: mapping values are not allowed in this context`

The values file contains:

``` yaml
podSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - all
```

The generated content is:
``` yaml
      securityContext:
        allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
```
 with a bad indentation (capabilities and allowPrivilegeEscalation should be aligned.

I tried with `{{ toYaml .Values.podSecurityContext | indent 10 | trim }}` instead of `{{ toYaml .Values.podSecurityContext | indent 12 | trim }}` the generation is OK

Indent should be 12 for Deployment (didn't need to update it) and 10 for statefulset ...
